### ISSUE TITLE
"Path does not exist"

### ISSUE THREAD

**Issue by bennofatius** [Yard1/facebookmessenger-exif#3]
First of all thank you for making this tool, it's exactly what I need (if I get it to work)! 

Issue: following your exact instructions, I receive an error saying "line 73 Path does not exist" although the path does exist and I've made sure there are no spelling errors. What could be the issue here? 

Thanks in advance!

**Comment by Yard1** [comment]
Hey, could you provide a screenshot of your folder with the path to it and the command you are using to run the script?

**Comment by bennofatius** [comment]
Yes for sure! Note I used my gf's old PC for this (running Windows 7), since I'm a Mac user (and figured this entire thing wouldn't work on a Mac, but correct me if I'm wrong)

![s2](https://user-images.githubusercontent.com/64141736/148784710-51951a28-376c-4ce3-8604-d452481a192e.png)

**Comment by bennofatius** [comment]
![s1](https://user-images.githubusercontent.com/64141736/148786541-809eec6c-a1fa-4504-8608-4696b16c0ab8.png)

**Comment by Yard1** [comment]
You need to have python 3.7 or higher to use this tool.

**Comment by bennofatius** [comment]
Thank for your response! I've updated Python and now the tool is starting. However, still experiencing issues. If you wouldn't mind having another look? Attaching both the error messages here as well as what my 'messages' folder contains.
![IMG_8222](https://user-images.githubusercontent.com/64141736/149153067-c1a49f89-0466-4d12-b799-30ccb8402759.jpg)

![IMG_8223](https://user-images.githubusercontent.com/64141736/149152906-76f31e30-bbc0-441e-ac27-fe0db73cd9a9.jpg)
94db.jpg)

**Comment by Zankoas** [comment]
> You need to have python 3.7 or higher to use this tool.

Opened a pull request to make this clear: https://github.com/Yard1/facebookmessenger-exif/pull/4
